version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  App.web.api:
    image: ${DOCKER_REGISTRY-}appwebapi
    build:
      context: .
      dockerfile: App.Web.API/Dockerfile
    environment:
      DB_CONNECTION_STRING: ""      
    networks:
      - dockerapi-dev
    ports:
      - "5000:443"
      - "5001:80"
  redis_image:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - dockerapi-dev
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - dockerapi-dev
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    ports:
      - "5601:5601"
    networks:
      - dockerapi-dev
    depends_on:
      - elasticsearch
volumes:
  esdata:
     driver: local